name: linos
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.2
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.4
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  go_router: ^15.1.2
  equatable: ^2.0.7
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  get_it: ^8.0.3
  injectable: ^2.3.2
  geolocator: ^14.0.1
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  rxdart: ^0.28.0
  google_polyline_algorithm: ^3.1.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#417AA1" 
  image: "assets/png/linos_logo4x.png" 
  android_12:
    image: "assets/png/linos_logo4x.png" 

  android_gravity: center 
  ios_content_mode: scaleAspectFill 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/linos_logo4x.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
